name: deploy arm64 snap

on:
  workflow_run:
    workflows:
      - snap_arm64
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

    steps:
      - name: deploy
        run: |
          snapcraft upload ~/ci-artifacts/wick_arm64.snap