name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: check go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - run: go version

      - name: check build
        run: |
          make deps
          make build