
name: build snap

on:
  push:
    branches:  
      - main 
  pull_request:
    branches: 
      - main 

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: setup snapcraft
        run: |
         sudo lxd init --auto 
         sudo snap install snapcraft --classic
         sudo chown $USER:$USER /var/snap/lxd/common/lxd/unix.socket
         
      - name: build snap
        run:  snapcraft --use-lxd
